name: Build & Push Nuxt App to Amazon ECR

run-name: Run triggered by ${{ github.event_name }} with commit message ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build --secret id=db-url-id,env=DATABASE_URL -t blogpost-app .
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Tag Docker image
        run: |
          docker tag blogpost-app:latest ${{ vars.ECR_REPOSITORY_URI }}:${{ vars.IMAGE_TAG }}

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ vars.ECR_REPOSITORY_URI }}:${{ vars.IMAGE_TAG }}
