name: Build & Push Nuxt App to Amazon ECR

run-name: Run triggered by ${{ github.event_name }} with commit message ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Tag Docker image
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          IMAGE_TAG: ${{ vars.IMAGE_TAG }}
        id: build-and-tag
        shell: bash
        run: |
          docker build --secret id=db-url-id,env=DATABASE_URL -t $IMAGE_TAG .
          echo "IMAGE $IMAGE_TAG is built and tagged"

      - name: Push Docker image to Amazon ECR
        id: push
        shell: bash
        env:
          ECR_REPOSITORY_URI: ${{ vars.ECR_REPOSITORY_URI }}
          IMAGE_TAG: ${{ vars.IMAGE_TAG }}
        run: |
          docker push "$ECR_REPOSITORY_URI:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REPOSITORY_URI"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REPOSITORY_URI:$IMAGE_TAG"
